"""add on delete to parent table

Revision ID: 0f64d635b4b0
Revises: 66c16d401162
Create Date: 2025-01-22 11:16:05.354566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f64d635b4b0'
down_revision = '66c16d401162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_constraint('parents_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('parents_student_id_fkey', 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###
